const path = require('path');
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('@react-native/metro-config').MetroConfig}
 */
const config = {
  resolver: {
    // Map the virtual 'rnwl-config' module to the rnwl.json generated by
    // `npx rnwl apply-white-label`. This lets react-native-whitelabel read the
    // active brand config without hardcoding a path inside node_modules.
    extraNodeModules: {
      'rnwl-config': path.resolve(__dirname, 'rnwl.json'),
    },
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
